server:
  port: 8080
spring:
  application:
    name: AI-Recruiter-backend
  output:
    ansi:
      enabled: ALWAYS
  ai:
    openai:
      api-key: must-be-provided
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  swagger-ui:
    operationsSorter: alpha
